package com.project.grcplatform.constant;

public enum AuditAction {
    // Assets
    ASSET_CREATED, ASSET_UPDATED, ASSET_DELETED, ASSET_LIFECYCLE_CHANGED,
    ASSET_INCIDENT_CREATED, ASSET_INCIDENT_UPDATED, ASSET_INCIDENT_DELETED,

    // Vulnerabilities
    VULNERABILITY_CREATED, VULNERABILITY_UPDATED, VULNERABILITY_DELETED,
    VULNERABILITY_VALIDATED, VULNERABILITY_STATUS_CHANGED,

    // Threats
    THREAT_CREATED, THREAT_UPDATED, THREAT_DELETED, THREAT_VALIDATED, THREAT_REVIEWED,

    // Scenarios
    SCENARIO_CREATED, SCENARIO_UPDATED, SCENARIO_DELETED,
    SCENARIO_SUBMITTED, SCENARIO_VALIDATED, SCENARIO_ARCHIVED, SCENARIO_REVIEWED,
    SCENARIO_INCIDENT_CREATED, SCENARIO_INCIDENT_UPDATED, SCENARIO_INCIDENT_DELETED,

    // Assessments
    ASSESSMENT_CREATED, ASSESSMENT_UPDATED, ASSESSMENT_DELETED,
    ASSESSMENT_STARTED, ASSESSMENT_SUBMITTED, ASSESSMENT_COMPLETED, ASSESSMENT_ARCHIVED,
    ASSESSMENT_SCENARIO_ADDED, ASSESSMENT_SCENARIO_REMOVED,

    // Treatment Plans
    TREATMENT_PLAN_CREATED, TREATMENT_PLAN_UPDATED, TREATMENT_PLAN_DELETED,
    TREATMENT_PLAN_APPROVED, TREATMENT_PLAN_STARTED, TREATMENT_PLAN_COMPLETED, TREATMENT_PLAN_CANCELLED,

    // Actions
    ACTION_CREATED, ACTION_UPDATED, ACTION_DELETED, ACTION_COMPLETED, ACTION_CANCELLED,

    // Controls
    CONTROL_CREATED, CONTROL_UPDATED, CONTROL_DELETED,
    CONTROL_IMPLEMENTED, CONTROL_VALIDATED, CONTROL_RETIRED, CONTROL_REVIEWED,

    // Reports
    REPORT_GENERATED, REPORT_REGENERATED, REPORT_DELETED,

    // Notifications
    NOTIFICATION_READ, NOTIFICATION_DELETED,

    // Users / Auth
    USER_LOGIN, USER_LOGOUT, USER_LOGIN_FAILED,
    USER_CREATED, USER_UPDATED, USER_DELETED,

    // KRI
    KRI_CREATED, KRI_UPDATED, KRI_VALUE_UPDATED, KRI_DELETED,

    // Governance — Policies
    GOVERNANCE_POLICY_CREATED, GOVERNANCE_POLICY_UPDATED, GOVERNANCE_POLICY_DELETED,
    GOVERNANCE_POLICY_SUBMITTED, GOVERNANCE_POLICY_APPROVED, GOVERNANCE_POLICY_DEPRECATED,

    // Governance — Responsibilities
    GOVERNANCE_RESPONSIBILITY_CREATED, GOVERNANCE_RESPONSIBILITY_UPDATED, GOVERNANCE_RESPONSIBILITY_DELETED,

    // Governance — Documents
    GOVERNANCE_DOCUMENT_CREATED, GOVERNANCE_DOCUMENT_UPDATED, GOVERNANCE_DOCUMENT_DELETED,
    GOVERNANCE_DOCUMENT_PUBLISHED, GOVERNANCE_DOCUMENT_ARCHIVED, GOVERNANCE_DOCUMENT_OBSOLETE,

    // Compliance — Frameworks
    COMPLIANCE_FRAMEWORK_CREATED, COMPLIANCE_FRAMEWORK_UPDATED,
    COMPLIANCE_FRAMEWORK_DEPRECATED, COMPLIANCE_FRAMEWORK_DELETED,

    // Compliance — Requirements
    COMPLIANCE_REQUIREMENT_CREATED, COMPLIANCE_REQUIREMENT_UPDATED, COMPLIANCE_REQUIREMENT_DELETED,

    // Compliance — Evaluations
    COMPLIANCE_EVALUATION_CREATED, COMPLIANCE_EVALUATION_UPDATED, COMPLIANCE_EVALUATION_DELETED,
    COMPLIANCE_EVALUATION_STARTED, COMPLIANCE_EVALUATION_COMPLETED, COMPLIANCE_EVALUATION_CANCELLED,
    COMPLIANCE_ITEM_ADDED,

    // Compliance — Action Plans
    COMPLIANCE_ACTION_PLAN_CREATED, COMPLIANCE_ACTION_PLAN_UPDATED, COMPLIANCE_ACTION_PLAN_DELETED,
    // Audit métier
    AUDIT_CAMPAIGN_CREATED, AUDIT_CAMPAIGN_UPDATED, AUDIT_CAMPAIGN_DELETED,
    AUDIT_CAMPAIGN_STARTED, AUDIT_CAMPAIGN_SUBMITTED, AUDIT_CAMPAIGN_COMPLETED, AUDIT_CAMPAIGN_CANCELLED,
    AUDIT_CHECKLIST_ITEM_CREATED, AUDIT_CHECKLIST_ITEM_UPDATED, AUDIT_CHECKLIST_ITEM_DELETED,
    AUDIT_FINDING_CREATED, AUDIT_FINDING_UPDATED, AUDIT_FINDING_DELETED, AUDIT_FINDING_STATUS_CHANGED,
    AUDIT_RECOMMENDATION_CREATED, AUDIT_RECOMMENDATION_UPDATED, AUDIT_RECOMMENDATION_DELETED,
    AUDIT_RECOMMENDATION_STATUS_CHANGED,

    // Impact Evaluations
    IMPACT_EVALUATION_CREATED, IMPACT_EVALUATION_UPDATED, IMPACT_EVALUATION_DELETED,
    IMPACT_EVALUATION_OVERRIDDEN,

    // Scenario Priority Config
    PRIORITY_CONFIG_CREATED, PRIORITY_CONFIG_UPDATED, PRIORITY_CONFIG_DELETED,
    PRIORITY_CONFIG_ACTIVATED,

    // Threat Watch
    THREAT_WATCH_SOURCE_CREATED, THREAT_WATCH_SOURCE_UPDATED, THREAT_WATCH_SOURCE_DELETED,
    THREAT_WATCH_SOURCE_FETCHED,
    THREAT_WATCH_ENTRY_PROCESSED,

}