package com.project.grcplatform.constant;

public enum AuditEntityType {
    ASSET, VULNERABILITY, THREAT, SCENARIO, ASSESSMENT,
    TREATMENT_PLAN, ACTION, CONTROL, REPORT, NOTIFICATION, USER,
    KRI,
    GOVERNANCE_POLICY, GOVERNANCE_RESPONSIBILITY, GOVERNANCE_DOCUMENT,
    COMPLIANCE_FRAMEWORK, COMPLIANCE_REQUIREMENT,
    COMPLIANCE_EVALUATION, COMPLIANCE_ACTION_PLAN,
    AUDIT_CAMPAIGN,
    AUDIT_CHECKLIST_ITEM,
    AUDIT_FINDING,
    AUDIT_RECOMMENDATION,
    IMPACT_EVALUATION,
    THREAT_WATCH_SOURCE,
    THREAT_WATCH_ENTRY,
    PRIORITY_CONFIG
}