package com.project.grcplatform.constant;

public enum NotificationEntityType {
    ASSET, VULNERABILITY, THREAT, SCENARIO, ASSESSMENT,
    TREATMENT_PLAN, ACTION, CONTROL, REPORT,
    KRI,
    GOVERNANCE_POLICY, GOVERNANCE_RESPONSIBILITY, GOVERNANCE_DOCUMENT,
    COMPLIANCE_FRAMEWORK, COMPLIANCE_EVALUATION, COMPLIANCE_ACTION_PLAN,
    AUDIT_CAMPAIGN,
    AUDIT_FINDING,
    AUDIT_RECOMMENDATION
}