package com.project.grcplatform.constant;

public enum NotificationType {
    // Vulnerabilities
    VULNERABILITY_CREATED,
    VULNERABILITY_HIGH_CRITICALITY,

    // Assessments
    ASSESSMENT_CREATED,
    ASSESSMENT_STATUS_CHANGED,
    ASSESSMENT_DUE_SOON,

    // Treatment
    TREATMENT_PLAN_APPROVED,
    ACTION_ASSIGNED,
    ACTION_OVERDUE,

    // Controls
    CONTROL_REVIEW_OVERDUE,

    // Reports
    REPORT_READY,
    REPORT_FAILED,

    // KRI
    KRI_WARNING,
    KRI_BREACH,

    // Governance
    GOVERNANCE_POLICY_APPROVED,
    GOVERNANCE_POLICY_EXPIRING,
    RESPONSIBILITY_ASSIGNED,

    // Compliance
    COMPLIANCE_EVALUATION_COMPLETED,
    COMPLIANCE_SCORE_LOW,
    COMPLIANCE_ACTION_ASSIGNED,
    COMPLIANCE_ACTION_OVERDUE,
    // Audit métier
    AUDIT_CAMPAIGN_STARTED,
    AUDIT_CAMPAIGN_COMPLETED,
    AUDIT_FINDING_CRITICAL,
    AUDIT_RECOMMENDATION_ASSIGNED,
    AUDIT_RECOMMENDATION_OVERDUE,

    // Scenario prioritization
    SCENARIO_PRIORITY_ALERT
}